@echo off
echo Starting Backend...
start cmd /k "cd /d %~dp0backend && venv\Scripts\activate && uvicorn app.main:app --port 8000 --reload"

echo Starting Frontend...
start cmd /k "cd /d %~dp0frontend && npm run dev"

echo Both servers are starting...
