"""add_survival_mode_to_deck

Revision ID: 4afcbacc6d5e
Revises: d55d265b6a43
Create Date: 2026-07-22 21:42:46.553631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afcbacc6d5e'
down_revision: Union[str, Sequence[str], None] = 'd55d265b6a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('survival_wins', sa.Integer(), nullable=True))
    op.add_column('decks', sa.Column('next_wither_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('decks', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'last_reviewed_at')
    op.drop_column('decks', 'next_wither_at')
    op.drop_column('decks', 'survival_wins')
    # ### end Alembic commands ###
