""" Add missed_waterings table

Revision ID: 5e4935099b1f
Revises: 70862ff80086
Create Date: 2026-08-07 09:41:18.044031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4935099b1f'
down_revision: Union[str, Sequence[str], None] = '70862ff80086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missed_waterings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('deck_title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missed_waterings_date'), 'missed_waterings', ['date'], unique=False)
    op.create_index(op.f('ix_missed_waterings_id'), 'missed_waterings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missed_waterings_id'), table_name='missed_waterings')
    op.drop_index(op.f('ix_missed_waterings_date'), table_name='missed_waterings')
    op.drop_table('missed_waterings')
    # ### end Alembic commands ###
