"""add_wither_stage

Revision ID: 70862ff80086
Revises: 4afcbacc6d5e
Create Date: 2026-07-22 22:33:28.815186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70862ff80086'
down_revision: Union[str, Sequence[str], None] = '4afcbacc6d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('wither_stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'wither_stage')
    # ### end Alembic commands ###
