"""update_study_progress_for_srs

Revision ID: d55d265b6a43
Revises: e30ca79f4a13
Create Date: 2026-07-21 00:44:27.233548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd55d265b6a43'
down_revision: Union[str, Sequence[str], None] = 'e30ca79f4a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_progress', sa.Column('step_corrects', sa.Integer(), nullable=True))
    op.add_column('study_progress', sa.Column('target_corrects', sa.Integer(), nullable=True))
    op.add_column('study_progress', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('study_progress', 'review_count')
    op.drop_column('study_progress', 'next_review_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_progress', sa.Column('next_review_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('study_progress', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('study_progress', 'last_reviewed_at')
    op.drop_column('study_progress', 'target_corrects')
    op.drop_column('study_progress', 'step_corrects')
    # ### end Alembic commands ###
